### ISSUE TITLE
Google Consent Mode [Feature Request]

### ISSUE THREAD

**Issue by mikeemike7** [w4holding/w4_cookiebar#1]
Google Consent Mode Integration (Feature Request)

Hi, it would be nice (essential for comercial use) to have a tracking without consent.
When do you support google consent mode?
Greets from Münster, M.

**Comment by w4holding** [comment]
Mike, the purpose of this extension is to make easy for editors to insert code that will be executed or displayed only when the user consents, if you want tu execute some code without the user consent you can just go the usual way, inserting it in the html header with TypoScript or in the body with a html content element.
