### ISSUE TITLE
Log being flooded due to parsing error

### ISSUE THREAD

**Issue by bni-tm** [w4holding/w4_cookiebar#2]
My log has recently been flooded with errors relating to this plugin:

ERROR] request="ee8d586891687" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"applicationContext matches \"/^Production/\" && {$gtm.embed} == 1"}

Caused by lib.gtm.setup.typoscript line 4

**Comment by w4holding** [comment]
It has been fixed, thanks to [grifmo](https://github.com/grifmo)
